/*
 * Ski Data API for NEU Seattle distributed systems course
 * An API for an emulation of skier managment system for RFID tagged lift tickets. Basis for CS6650 Assignments for 2019
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
import java.util.Random;

/**
 * LiftRideInfo
 * Used to send a client request with a liftRideInfo instance
 */


public class LiftRideInfo {
  LiftRide body;
  Integer resortID;
  String seasonID;
  String dayID;
  Integer skierID;

  public LiftRideInfo(Random r) {
    this.body = new LiftRide(r.nextInt(360) + 1, r.nextInt(40) + 1);
    this.resortID = r.nextInt(10) + 1;
    this.seasonID = "2024";
    this.dayID = "1";
    this.skierID = r.nextInt(10000) + 1;
  }

  public LiftRide getBody() {
    return body;
  }

  public void setBody(LiftRide body) {
    this.body = body;
  }

  public Integer getResortID() {
    return resortID;
  }

  public void setResortID(Integer resortID) {
    this.resortID = resortID;
  }

  public String getSeasonID() {
    return seasonID;
  }

  public void setSeasonID(String seasonID) {
    this.seasonID = seasonID;
  }

  public String getDayID() {
    return dayID;
  }

  public void setDayID(String dayID) {
    this.dayID = dayID;
  }

  public Integer getSkierID() {
    return skierID;
  }

  public void setSkierID(Integer skierID) {
    this.skierID = skierID;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (!(o instanceof LiftRideInfo)) return false;
    LiftRideInfo that = (LiftRideInfo) o;
    return getBody().equals(that.getBody()) && getResortID().equals(that.getResortID()) && getSeasonID().equals(that.getSeasonID()) && getDayID().equals(that.getDayID()) && getSkierID().equals(that.getSkierID());
  }

  @Override
  public int hashCode() {
    return Objects.hash(getBody(), getResortID(), getSeasonID(), getDayID(), getSkierID());
  }

  @Override
  public String toString() {
    return "LiftRideInfo{" +
            "body=" + body +
            ", resortID=" + resortID +
            ", seasonID='" + seasonID + '\'' +
            ", dayID='" + dayID + '\'' +
            ", skierID=" + skierID +
            '}';
  }
}
