/*
 * Ski Data API for NEU Seattle distributed systems course
 * An API for an emulation of skier managment system for RFID tagged lift tickets. Basis for CS6650 Assignments for 2019
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import clients.client1.Client1Runnable;
import clients.client2.Client2Runnable;
import io.swagger.client.model.SkierVertical;
import org.junit.Test;
import org.junit.Ignore;


import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;

import static clients.client1.Client1ThreadHelper.client1StartNThreads;
import static clients.client2.Client2ThreadHelper.client2StartNThreads;


/**
 * API tests for SkiersApi
 */
@Ignore
public class SkiersApiTest {

    private final SkiersApi api = new SkiersApi();

    /**
     * write a new lift ride for the skier
     *
     * get the total vertical for the skier for the specified ski day
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getSkierDayVerticalTest() throws Exception {
        Integer resortID = null;
        String seasonID = null;
        String dayID = null;
        Integer skierID = null;
        Integer response = api.getSkierDayVertical(resortID, seasonID, dayID, skierID);

        // TODO: test validations
    }
    /**
     * get the total vertical for the skier for specified seasons at the specified resort
     *
     * get the total vertical for the skier the specified resort. If no season is specified, return all seasons
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getSkierResortTotalsTest() throws Exception {
        Integer skierID = null;
        List<String> resort = null;
        List<String> season = null;
        SkierVertical response = api.getSkierResortTotals(skierID, resort, season);

        // TODO: test validations
    }
    /**
     * write a new lift ride for the skier
     *
     * Stores new lift ride details in the data store
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void writeNewLiftRideTest() throws Exception {

    }

    @Test
    public void client1SingleRequestTimeTest() throws Exception {
        long wallTime = client1StartNThreads(8, 674);
        System.out.println("total run time (wall time) for 10000 request/thread to complete: " + 1.0*wallTime/1000 + " seconds");
        System.out.println("run time (wall time) per request: " + 1.0*wallTime/ Client1Runnable.getSuccessCounter() + " milliseconds per request");
    }

    @Test
    public void client2SingleRequestTimeTest() throws Exception {
        try(BufferedWriter bf = new BufferedWriter(new FileWriter("test.csv"))) {
            clients.client2.Client2Runnable.setBf(bf);
            bf.write("Start Time,Request Type,Latency,Response Code\n");
            long wallTime =client2StartNThreads(1, 10000, bf);
            System.out.println("total run time (wall time) for 10000 request/thread to complete: " + 1.0*wallTime/1000 + " seconds");
            System.out.println("run time (wall time) per request: " + 1.0*wallTime/Client2Runnable.getSuccessCounter() + " milliseconds per request");
        } catch(IOException e) {
            e.printStackTrace();
        }
    }
}
